python train_llm.py \
    --new_quant \
    --batch_size 2048 \
    --max_steps 5000 \
    --codebook_bits 16 \
    --codebook_dim 8 \
    --quantizer_type BSQ \
    --optimizer adamw \
    --recon_loss_type mse \
    --lr 1e-4 \
    --eval_every 100 \
    --lfq_weight 4 \
    --image_gan_weight 0.3 \
    --discriminator_iter_start 0 \
    --decoder_type symmetric \
    --normalize_data \
    --clip_threshold 0 \
    --wandb_project LLM_MultiVAE_VQ \
    --default_root_dir ./logs/llm_lfq_vq \
    --parallel_layers 32 $@