"""VAELLM document inventory/search/link checks; standard library only."""
import argparse
import os
from pathlib import Path
import re
from urllib.parse import quote, unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
INDEX = Path('docs/INDEX.md')
SKIP = {'.git', '.cache', '__pycache__', '.pytest_cache', '.venv', 'venv', 'node_modules'}
SUFFIXES = {'.md', '.mdc', '.rst', '.txt', '.org', '.adoc', '.html', '.pdf', '.docx', '.ipynb'}
NON_DOCS = {'requirements.txt', 'merges.txt', 'vocab.txt', 'started_at.txt'}
LABELS = {
    'active': '规则、导航与使用说明', 'lessons': '可复用经验',
    'records': '实验结果与验证记录', 'history': '历史计划与审查',
    'artifacts': '原位产物说明与自动报告', 'bridge': '工具交接状态（非长期知识）',
    'external': '第三方说明与许可证',
}


def category(p):
    s = p.as_posix()
    for part in ('lessons', 'records', 'history'):
        if s.startswith('docs/experience/' + part + '/'):
            return part
    if s.startswith('.ai-bridge/'):
        return 'bridge'
    if s.startswith(('result/', '.result/')):
        return 'artifacts'
    if s.startswith('HiFloat4/') or p.name.upper().startswith(('LICENSE', 'COPYING', 'NOTICE')):
        return 'external'
    return 'active'


def inventory(root):
    docs, aliases = [], []
    for base, dirs, files in os.walk(root, followlinks=False):
        dirs[:] = sorted(d for d in dirs if d not in SKIP and not (Path(base) / d).is_symlink())
        for name in sorted(files):
            p = Path(base) / name
            if name in NON_DOCS or not (p.suffix.lower() in SUFFIXES or name.upper().startswith(('LICENSE', 'COPYING', 'NOTICE'))):
                continue
            rel = p.relative_to(root)
            (aliases if p.is_symlink() else docs).append(rel)
    return sorted(docs), sorted(aliases)


def read(root, p):
    if p.suffix.lower() in ('.pdf', '.docx'):
        return ''
    return (root / p).read_text(encoding='utf-8', errors='replace')


def title(root, p):
    text = read(root, p)
    m = re.search(r'^#\s+(.+)$', text, re.M) or re.search(r'<title>(.*?)</title>', text, re.S | re.I)
    return re.sub(r'[\[\]<>`\r\n]', '', m[1]).strip() if m else p.name


def link(p):
    return quote(os.path.relpath(p, INDEX.parent).replace(os.sep, '/'), safe='/._-')


def render(root, docs, aliases):
    rows = ['# 全项目文档目录', '', '<!-- Generated by python tools/docs.py index; do not edit. -->', '',
            '日常从 [任务入口](README.md) 开始；本表按文件位置自动分类，不表示内容已经验证或任务已经完成。',
            '不遍历目录符号链接，不收录依赖/缓存、tokenizer 文本、运行时间标记及原始 JSON/日志。',
            '旧路径只列映射，不重复索引正文；历史迁移来源另见 [CATALOG](experience/CATALOG.md)。', '']
    for group, label in LABELS.items():
        selected = [p for p in docs if category(p) == group and p != INDEX]
        rows += [f'## {label}（{len(selected)}）', '']
        rows += [f'- [{title(root, p)}]({link(p)}) — `{p.as_posix()}`' for p in selected]
        rows += ['']
    rows += [f'## 旧路径映射（{len(aliases)}）', '']
    for p in aliases:
        target = (root / p).resolve()
        destination = target.relative_to(root) if target.is_relative_to(root) else target
        rows.append(f'- `{p.as_posix()}` → [{destination.as_posix()}]({link(destination)})')
    return '\n'.join(rows) + '\n'


def markdown_targets(text):
    text = re.sub(r'^\s*(`{3,}|~{3,})[^\n]*\n.*?^\s*\1\s*$', '', text, flags=re.M | re.S)
    text = re.sub(r'`+[^`\n]*`+', '', text)
    # Repository uses ordinary inline links and reference definitions. Anchors and URLs are not checked.
    yield from re.findall(r'\]\(<?([^\s)>]+)>?(?:\s+"[^"]*")?\)', text)
    yield from re.findall(r'^\s*\[[^\]]+\]:\s*<?([^\s>]+)>?', text, re.M)


def check(root, docs, aliases):
    errors, count = [], 0
    for p in aliases:
        target = (root / p).resolve()
        if not target.is_relative_to(root) or not target.is_file():
            errors.append(f'{p}: broken or external alias')
    for p in docs:
        if p.suffix != '.md':
            continue
        for dest in markdown_targets(read(root, p)):
            url = urlsplit(dest)
            if url.scheme or url.netloc or not url.path or url.path.startswith('/'):
                continue
            count += 1
            if not (root / p.parent / unquote(url.path)).exists():
                errors.append(f'{p}: missing {dest}')
    print(f'canonical={len(docs)} aliases={len(aliases)} relative_markdown_paths={count} errors={len(errors)}')
    for error in errors:
        print(error)
    return bool(errors)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='command', required=True)
    index = sub.add_parser('index', help='Regenerate deterministic docs/INDEX.md')
    index.add_argument('--check', action='store_true', help='Check index freshness without writing')
    sub.add_parser('check', help='Check aliases and relative Markdown file targets; not anchor/URL validity')
    search = sub.add_parser('search', help='Search canonical text only; default excludes result/history noise')
    search.add_argument('pattern', help='Case-insensitive regular expression')
    search.add_argument('--scope', choices=['default', 'all', *LABELS], default='default')
    search.add_argument('--limit', type=int, default=40, help='Maximum matching lines; 0 for unlimited')
    args = parser.parse_args()
    docs, aliases = inventory(ROOT)
    if args.command == 'check':
        return check(ROOT, docs, aliases)
    if args.command == 'index':
        result = render(ROOT, docs, aliases)
        path = ROOT / INDEX
        if args.check:
            good = path.exists() and path.read_text(encoding='utf-8') == result
            print('INDEX up to date' if good else 'INDEX stale: run python tools/docs.py index')
            return not good
        path.write_text(result, encoding='utf-8')
        print(f'{INDEX}: {len(docs) - int(INDEX in docs)} documents + {len(aliases)} aliases')
        return 0
    try:
        pattern = re.compile(args.pattern, re.I)
    except re.error as e:
        parser.error(str(e))
    scope = {'active', 'lessons'} if args.scope == 'default' else set(LABELS) if args.scope == 'all' else {args.scope}
    found = 0
    for p in docs:
        if category(p) not in scope or p in (INDEX, Path('docs/experience/CATALOG.md')):
            continue
        for number, line in enumerate(read(ROOT, p).splitlines(), 1):
            if pattern.search(line):
                print(f'{p.as_posix()}:{number}: {line[:600]}')
                found += 1
                if args.limit > 0 and found >= args.limit:
                    print('Match limit reached; refine pattern/scope or use --limit 0.')
                    return 0
    if not found:
        print('No matches in selected scope.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
